// Smoke test for the liburing module: exercises the patched/overlaid
// build (io_uring_version.h is generated by the overlay BUILD file).

#include <cstdio>
#include <cstdlib>

#include "liburing.h"

int main() {
  if (io_uring_major_version() != IO_URING_VERSION_MAJOR
      || io_uring_minor_version() != IO_URING_VERSION_MINOR) {
    fprintf(stderr, "liburing version mismatch\n");
    return EXIT_FAILURE;
  }
  printf("liburing %d.%d\n", io_uring_major_version(),
         io_uring_minor_version());
  return EXIT_SUCCESS;
}
