name: Publish release

permissions:
  contents: read

on:
  workflow_run:
    workflows:
    - Bazel registry CI
    types:
    - completed


jobs:
  publish:
    if: >-
      github.event.workflow_run.event == 'push'
      && github.event.workflow_run.conclusion == 'success'
    permissions:
      actions: read
      contents: write
    secrets:
      app-id: ${{ secrets.ENVOY_CI_PUBLISH_APP_ID }}
      app-key: ${{ secrets.ENVOY_CI_PUBLISH_APP_KEY }}
    uses: ./.github/workflows/_publish.yml
    with:
      committer-email: "140627008+publish-envoy[bot]@users.noreply.github.com"
      committer-name: "publish-envoy[bot]"
